CREATE TABLE mch_j9_data
(
patient_id int,
patient_age int ,
education_level varchar(255),
able_read_write bit,
date_enrolled datetime,
date_completed datetime,
program_state varchar(255),
mothers_group text,
expected_delivery_date datetime,
prior_birth_delivery_type varchar(255),
prior_birth_neonatal_status varchar(255),
history_pre_eclampsia bit,
history_eclampsia bit,
history_post_partum_hemorrhage bit,
history_gender_based_violence bit,
history_type_1_diabetes bit,
history_type_2_diabetes bit,
history_gestational_diabetes bit,
number_anc_visit int,
number_obGyn_visits int,
number_postpartum_visits int,
number_family_planning_visits int,
marital_status varchar(255),
employment_status varchar(255),
religion varchar(255),
family_support bit,
partner_support_anc bit,
number_living_children int,
number_household_members int,
address_department varchar(255),
address_commune varchar(255),
address_section_communale varchar(255),
address_locality varchar(255),
address_street_landmark varchar(255),
access_transport bit,
mode_transport varchar(255),
traditional_healer varchar(255),
prenatal_teas varchar(255)
);
